name: linting, testing
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [master]
  pull_request: 
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: run build prod
        run: npm run build:prod
      - name: lint ts files
        run: npm run lint:ts
      - name: lint scss
        run: npm run lint:scss